### PR TITLE
Fix file names for Minimize.png and Maximize.png asked for by plugin.gd

### PR DESCRIPTION
**Pull request by ghost**
Fixes a bug in plugin.gd that asks for Minimize.png and Maximize.png instead of minimize.png and maximize.png

renamed:    addons/gd_profiler/textures/Minimize.png -> addons/gd_profiler/textures/minimize.png
renamed:    addons/gd_profiler/textures/Minimize.png -> addons/gd_profiler/textures/maximize.png

### CODE REVIEW

**Comment by ghost** [comment]
lol

**Comment by lightyuwu** [comment]
I'm not really sure how necessary that is though...

**Comment by lightyuwu** [comment]
Besides, it seems like you forgot to change the code, as far as the pull request is saying

**Comment by ghost** [comment]
yeah lol i was really tired when doing that and had no idea what i was doing.

**Pull request closed without merging**
